### PR TITLE
Allow Ctrl+Return to run code

### PR DESCRIPTION
**Pull request by ahstro**
Allow pressing Ctrl and the Return key at any point to run the code in the editor instead of having to click submit or use up all lines and press Return.

### CODE REVIEW

**Comment by thomaspark** [comment]
This is a great suggestion. Could you make some minor tweaks to PR?

* Separate this as its own condition. Reason being that ctrl-return should submit no matter what, but if there's any whitespace before or after, it will be trimmed instead.
* Have it be the first condition, again so it's guaranteed to submit.
* Also check for `e.metaKey` for Mac.

**Comment by ahstro** [comment]
Like this? :)

**Comment by thomaspark** [comment]
:+1: Looks good, thanks for this!

**Comment by ahstro** [comment]
No problem, thank you for a great resource :)

**Pull request merged**
