### PR TITLE
Add Latvian translations

### PR DESCRIPTION
**Pull request by Akirtovskis**
Added Latvian translations. 

Deletions that show up in files are simply added commas after Macedonian translations. I re-did this twice, thinking that it may have been something on my end, only to realize that everything seems to work fine, just difference looks weird. If anyone has suggestions how to avoid this here or in future, let me know.

This is my first contribution to open source and I picked this project because it really helped me to improve my knowledge and application of CSS flexbox.

### CODE REVIEW

**Comment by thomaspark** [comment]
Hey @Akirtovskis, welcome to the open source world and thanks for your contribution!

Adding a comma will display like that so no need to worry or do anything different. The translation looks good, but there are a few spots in `levels.js` where you added a line return in the middle of the string:

* [line 75](https://github.com/thomaspark/flexboxfroggy/pull/135/files#diff-118461f2d0f90667d59f0beb7dc2deabR75)
* [line 196](https://github.com/thomaspark/flexboxfroggy/pull/135/files#diff-118461f2d0f90667d59f0beb7dc2deabR196)
* [line 843](https://github.com/thomaspark/flexboxfroggy/pull/135/files#diff-118461f2d0f90667d59f0beb7dc2deabR843)

Can you delete the returns so all the text is on a single line? You make make a new commit for it, then I'll merge in your work. Let me know if you have any questions.

**Comment by thomaspark** [comment]
Looks like you missed one at line 841. Otherwise looks ready to go!

**Comment by Akirtovskis** [comment]
Thanks, though right now it still shows english version when I choose Latvian on the site!

**Comment by Akirtovskis** [comment]
Yes, that was the case! Thanks!

**Pull request merged**
