### PR TITLE
Added Serbian translation

### PR DESCRIPTION
**Pull request by dankoknad**
Hi Thomas, 

I liked your Flexbox Froggy so much that I decided to translate it to my native language - Serbian. 

Thank you for your hard work and awesome idea.

Best,
Danko

### CODE REVIEW

**Comment by thomaspark** [comment]
Hey Danko, thanks for this! I'll do a more thorough review soon, but can you make one quick change? Change the language key from `ser` to `sr`, which is the [official ISO code](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) for Serbian.

**Comment by dankoknad** [comment]
Hey Thomas, it's done! If you need me to make more adjustments, I will be happy to do it.

**Comment by thomaspark** [comment]
Thanks, just one more thing I spotted. You missed the translation at the end of `levels.js`: https://github.com/dankoknad/flexboxfroggy/blob/cba3379d25736cd68af64b76760cf8f60cab4e57/js/levels.js#L805

Otherwise, looks good to go!

**Comment by dankoknad** [comment]
Good catch! Since I have been translating from English, maybe a word "hoppy" also need correction: 
https://github.com/dankoknad/flexboxfroggy/blob/gh-pages/js/levels.js#L759 ?

**Comment by thomaspark** [comment]
Merged! Danko, much thanks for your contribution.

**Comment by dankoknad** [comment]
Awesome! It was my pleasure, Thomas.

**Pull request merged**
