### PR TITLE
Feature to write CSS property when click property value in tooltip

### PR DESCRIPTION
**Pull request by qowlz**
Based on the idea presented in #131, my team created feature that writing CSS property when click tooltip value item!
If you look at the image below, you can intuitively understand it.

Animation

And there were additional code changes as follows.
- Disabled `next` button in case of incorrect answer when calling `game.check`. Because `game.check` was called every time the css property was clicked.
- Added cover behind tooltip. This is to prevent other tooltip from appearing when clicking on the property value in tooltip.

I'll be waiting for  your review and approval.
Thank you!

### CODE REVIEW

**Comment by qowlz** [comment]
Hello @thomaspark I guess you're busy.😂 Can you review this PR when you have time?

**Comment by thomaspark** [comment]
Hey @qowlz, sorry for the delayed review! Overall, it's working well. Thanks so much. Just a couple points of discussion:

* Playing around with it made me realize the tooltip behavior is inconsistent (it was inconsistent before too). `mouseenter` opens the tooltip, `mouseleave` doesn't close it, `click` once closes it, `click` again doesn't open it. What if we used clicks as the main interaction, and remove the hover behavior entirely? An added benefit of this is that it would work on mobile, where the new feature is most useful.
* Clicking the levels menu repeatedly no longer toggles it closed. This can be fixed by reverting line 114 in `game.js`.
*  At line 353, there's this line: `$("code").css('cursor', 'pointer');`. How about we move it to see and scope it to the tooltip using the selector `.tooltip code`?

Let me know your thoughts.

**Comment by qowlz** [comment]
Hey @thomaspark Thank you for review! 
My thoughts on the suggestions are as follows.
1. I think that is great suggestion! I'll fix it like that.
2. `game.js` line 114 should be `toggle` instead of `show`. I'll fix it soon.
3. I'll fix this part as you said

**Comment by qowlz** [comment]
Hey @thomaspark I'm done above changes. I'd appreciate it if you could review it. :)

**Comment by thomaspark** [comment]
Hey @qowlz, I like the changes we made. Thanks for your team's hard work.

A couple more things I noticed:

* When clicking the shorthand property `flex-flow`, it's filled with `flex-flow: <flex-direction>;`. Something like `flex-flow: row nowrap` would work better, which are the defaults.
* A tricky issue is that when the existing input code isn't perfectly formed, there's some buggy behavior. For example, when the input is:
```css
flex-direction: ;
order: 5;
```

And we click a tooltip like `justify-content: center`, the input becomes:
```css
flex-direction: order;
order: 5;
justify-content: center;
```

And some quick usability improvements:
* After clicking a tooltip, let's focus the input field again.
* When the level menu is open and we open a code tooltip, let's close the level menu since it can block the tooltip.

**Comment by qowlz** [comment]
Thank you for review and bug reporting!
I'll fix everything you told.

**Comment by qowlz** [comment]
Hey @thomaspark, I'm done task you said. I look forward to your review. :)

**Comment by moo-nerim** [comment]
Hello @thomaspark , we've been waiting for your reply for almost a month. 😂
I'm really sorry, but can you confirm just one more time?

**Comment by thomaspark** [comment]
Hi all,

The new feature is working super! I just noticed two things in my testing:

1. When clicking a property name that's mentioned inside the tooltip (`align-items` for `align-self`, `flex-direction` and `flex-wrap` for `flex-flow`), the behavior is buggy.

    For example, clicking `align-items` inside the `align-self` tooltip will add `align-self: align-items;` the first time. Additional clicks will append `align-items: ;` each time.

    I think the expected behavior would be either to fill in the clicked property with its default value, or ignore the click. What do you think?

2. Instead of setting `cursor: pointer;` in JS on line 373, how about we move it to the CSS?

**Comment by qowlz** [comment]
Hi @thomaspark 
First, Thank you for review and testing! 
My thoughts on the cases that you told as follows.
1. In this case, I think it's better to ignore the click. I will change the code to ignore the click.
2. That's good idea. I will move that

**Comment by qowlz** [comment]
Hey @thomaspark 
I finished editing code!
I'll be waiting for your quick review. :)

**Comment by thomaspark** [comment]
Hi @qowlz, it looks ready to go! Thanks to you and @dayo2n, @moo-nerim, @2Ju0 for your major contribution.

**Pull request merged**
