### PR TITLE
add simplified Chinese translation

### PR DESCRIPTION
**Pull request by timguoqk**

### CODE REVIEW

**Comment by thomaspark** [comment]
Many thanks for this, @timguoqk!

**Comment by thomaspark** [comment]
@timguoqk, just spotted that a translation for "Level" is missing here: https://github.com/thomaspark/flexboxfroggy/blob/gh-pages/js/messages.js#L32

Can you provide one?

**Comment by timguoqk** [comment]
I intentionally leave it that way! It's a little hard to explain but basically in Chinese "level one" doesn't make sense. "The first level" is correct. "Level" is a pretty basic word and imo it should be fine.

**Comment by thomaspark** [comment]
Ah, thanks for the clarification.

**Pull request merged**
