### PR TITLE
add Thai language

### PR DESCRIPTION
**Pull request by anurat**

### CODE REVIEW

**Comment by thomaspark** [comment]
Hi @anurat, thanks so much for the Thai translation. Can you exclude `package-lock.json` from this PR? Otherwise looks good to go.

**Comment by anurat** [comment]
hi @thomaspark, I removed package-lock.json.

Cheers,

**Comment by thomaspark** [comment]
Hi @anurat, sorry I meant to revert the changes you made to `package-lock.json` or exclude it from the pull request, not delete the file. Once that's done, it will be ready to merge!

**Comment by anurat** [comment]
@thomaspark, I'm new to contributing on github, so please bear with me.
I believe I reverted the file to the version before.
Best,

**Comment by anurat** [comment]
@thomaspark, Hi Thomas, is there anything else you need me to do?
Best,

**Comment by thomaspark** [comment]
@anurat, looks good, I'll merge it now.

Thanks for the translation! I'm surprised that wasn't a Thai translation yet.

If you're interested, Grid Garden still needs Thai support. :smile:
https://github.com/thomaspark/gridgarden

**Comment by anurat** [comment]
Definitely, thanks for these fun great games!

**Pull request merged**
