### PR TITLE
Feature/easy medium hard modes

### PR DESCRIPTION
**Pull request by mcshiz**
When in hard mode hide instructions and go to random level, medium just hide instructions, easy normal

### CODE REVIEW

**Comment by thomaspark** [comment]
Hey @mcshiz, thanks for this pull request, looks good and I love the idea of randomizing levels on top of hiding the instructions.

One issue is that it won't be immediately obvious what the different levels do. How about if we do a pop-up (like for languages) for Beginner/Intermediate/Advanced with short descriptions of what each does. Would you be up for working on that?

**Comment by mcshiz** [comment]
Sure thing. Glad you like it

**Comment by mcshiz** [comment]
Ok, I added some directions to a tooltip like the languages

**Comment by thomaspark** [comment]
The menu looks great, just what I was hoping for.

I noticed a new bug with the padding of the properties tooltips. Aside from that, it looks good to go.

screen shot 2018-02-03 at 5 50 17 pm

**Comment by thomaspark** [comment]
Merged!

**Pull request merged**
