### PR TITLE
Telugu version of the flexbox froggy

### PR DESCRIPTION
**Pull request by Thunderbolt2-o**
I have recently learned flexbox with the help of the game designed by you which is flexbox froggy. Thanks for creating it by making it you made it so simple to learn 😀.  I thought of making a contribution to it in my mother tongue which is Telugu.

### CODE REVIEW

**Comment by sripavan12132** [comment]
nice.

**Comment by AnneAbhiram** [comment]
Ur a good Inspiration for me bro

**Comment by subashgogula24** [comment]
Good work bro.

**Comment by thomaspark** [comment]
Hey @Thunderbolt2-o, looks great. Merging it now, thanks for your contribution.

**Pull request merged**
