### PR TITLE
Added Estonian translation, et

### PR DESCRIPTION
**Pull request by sten9911**
'et' in javascript files and i accidentally changed index.html to estonian as well. Was quite a lot of work but you're welcome and I hope you use it in the live version :))

### CODE REVIEW

**Comment by thomaspark** [comment]
Hey @sten9911, this is great, thanks for the translation. Could you revert the changes to `index.html`. There's also a few more strings to translate in `docs.js` for the property pop-ups. Once those are done I can merge it in.

**Comment by sten9911** [comment]
Hello,

Of course, I will get it done first thing tomorrow. Just wanted to tell you
that we played your game in my web dev course so I decided to help you out
a bit :D.

Sincerely,
Sten

**Comment by sten9911** [comment]
Finished the estonian translation

**Comment by thomaspark** [comment]
Hey @sten9911 , looks like there's still some changes in `index.html` we need to revert. Otherwise the translation looks good.

**Comment by thomaspark** [comment]
Merging now!

**Pull request merged**
