### PR TITLE
Improvements in the images frog, lilypad //PNG to SVG // and interfaces colors

### PR DESCRIPTION
**Pull request by ralts00**
Redraw the frogs and improve a little color , and the contrast between them and the background , like the colors better code editor . :)

### CODE REVIEW

**Comment by thomaspark** [comment]
Hi @ralts00, thanks for the PR. Can you post some before/after screenshots?

**Comment by ralts00** [comment]
Hi @thomaspark  these are the changes before | after :D
flexboxfroggy changes

**Comment by thomaspark** [comment]
I like some of the changes, but would like to hold off on the stylistic changes for now, because there may be bigger color changes coming to make it more accessible to the colorblind. I do think the tweak to the yellow frog is an improvement.

**Comment by patrickgrey** [comment]
I was going to suggest SVG to create sharper images but I was beaten too it!! :smile: However, could I suggest that svg, if implemented, keeps the png files as a fallback for visitors with browsers that don't support svg. The technique is outlined here: https://css-tricks.com/a-complete-guide-to-svg-fallbacks/ under "Fallback for SVG ass CSS background-image" and the code would look like

```CSS
.lilypad.green .bg {
  background-image: url(../images/lilypad-green.png);
  background: url(../images/lilypad-green.svg), linear-gradient(transparent, transparent);
}
```
Happy to provide a pull request if/when implemented. Totally love this game by the way!

**Comment by Notuom** [comment]
@patrickgrey Is there such a browser that doesn't support SVG but supports flexboxes? I'm just wondering why one would bother to have a fallback in case SVG is unavailable when using an even newer technology as the core of the game.

Compatibility tables for reference:
* [http://caniuse.com/#feat=svg](SVG support table)
* [http://caniuse.com/#feat=flexbox](Flexbox support table)

**Comment by thomaspark** [comment]
Thanks for discussion, guys. Images have been switched to SVG (see #22).

**Pull request closed without merging**
